# Generated by Django 2.1.7 on 2019-02-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_logo',
        ),
    ]
