# Generated by Django 2.1.7 on 2019-03-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0006_remove_project_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
    ]
