# Generated by Django 2.1.7 on 2019-03-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0007_auto_20190301_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
