# Generated by Django 2.1.7 on 2019-03-04 13:24

import conversion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0009_auto_20190304_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=conversion.models.user_directory_path),
        ),
    ]
