# Generated by Django 2.1.7 on 2019-03-06 08:42

import conversion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0010_auto_20190304_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FileField(upload_to=conversion.models.user_directory_path)),
            ],
        ),
    ]
