# Generated by Django 2.1.7 on 2019-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0011_convertedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfolder',
            name='folder',
            field=models.FileField(upload_to='media/'),
        ),
    ]
