# Generated by Django 2.1.7 on 2019-03-08 08:13

import conversion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0012_auto_20190307_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfolder',
            name='folder',
            field=models.FileField(upload_to=conversion.models.user_converted_directory_path),
        ),
    ]
